### PR TITLE
Fix password change url for 1.9

### PR DESCRIPTION
**Pull request by bmon**
The admin password change url for users [changed in django 1.9](https://docs.djangoproject.com/en/1.9/releases/1.9/#minor-features). This patch provides the corrected link for 1.9 upward.

### CODE REVIEW

**Review by bmon — COMMENTED** [review]
Removes a debugger statement left in by accident

**Comment by bennylope** [comment]
Thanks Brendan - if you can get it to pass that last check I'll merge this in.

**Comment by bmon** [comment]
Hi @bennylope, passing all tests now. Thanks!

**Comment by bennylope** [comment]
Thanks! Should get this up on PyPI shortly

**Pull request merged**
